In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import sys  
sys.path.append("/Users/caihao/PycharmProjects/insight_project/")
from data.config import raw_data_dir, processed_data_dir, cleaned_data_dir
tweets_dir  = "/Users/caihao/Dropbox/TEMP/tweets/"

In [5]:
df.columns

Index(['permalink', 'name', 'homepage_url', 'category_list', 'market',
       'funding_total_usd', 'status', 'country_code', 'state_code', 'region',
       'city', 'funding_rounds', 'founded_at', 'founded_month',
       'founded_quarter', 'founded_year', 'first_funding_at',
       'last_funding_at', 'twitter_username', 'first2last_funding_days',
       'twit_since', 'twit_until', 'WILL', 'days_since_series_a', 'WHEN',
       'series_a_date', 'preA_timespan', 'postA_timespan', 'all_tweet_num',
       'preA_tweet_num', 'postA_tweet_num', 'preA_tweet_freq',
       'postA_tweet_freq', 'preA_tweet_avglength', 'postA_tweet_avglength',
       'preA_tweet_content_richness', 'postA_tweet_content_richness',
       'preA_tweet_interactiveness', 'postA_tweet_interactiveness',
       'status_feature', 'country_feature', 'age_feature',
       'days_since_first_funding', 'tweet_num_change', 'tweet_freq_change',
       'tweet_avglength_change', 'tweet_content_richness_change',
       'tweet_interactiv

In [8]:
# test logistic regression model as baseline.
df = pd.read_csv(processed_data_dir + '/companies_all_labeled.csv')
selected_features = ['funding_total_usd', 'status_feature', 'country_feature', 'age_feature', \
                     'days_since_first_funding', 'all_tweet_num', 'preA_tweet_num', 'postA_tweet_num', \
                     'preA_tweet_freq', 'postA_tweet_freq', 'preA_tweet_avglength', 'postA_tweet_avglength', \
                     'preA_tweet_content_richness', 'postA_tweet_content_richness', 'preA_tweet_interactiveness', \
                     'postA_tweet_interactiveness',  'tweet_num_change', 'tweet_freq_change',
                     'tweet_avglength_change', 'tweet_content_richness_change',
                     'tweet_interactiveness_change', 'WILL']
new_df = df[selected_features].copy()
X = new_df.iloc[:, :-1].values
y = new_df.iloc[:, -1].values
print(X.shape, y.shape)

(3847, 21) (3847,)


In [41]:
from sklearn.linear_model import LogisticRegressionCV
import numpy as np

# logistic regression with cross-validation.
# clf = LogisticRegressionCV(cv=5, random_state=0, multi_class='multinomial').fit(X, y)
clf = LogisticRegressionCV(
        Cs=list(np.power(10.0, np.arange(-10, 10)))
        ,penalty='l2'
        ,scoring='roc_auc'
        ,cv=5
        ,random_state=777
        ,max_iter=10000
        ,fit_intercept=True
        ,solver='newton-cg'
        ,tol=10
    )
clf.fit(X, y)


/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not c

/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not c

/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not c

/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not c

/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not c

/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not c

/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/anaconda3/envs/py3/lib/python3.7/site-packages/scipy/optimize/linesearch.py:462: LineSearchWarning: The line search algorithm did not c

LogisticRegressionCV(Cs=[1e-10, 1e-09, 1e-08, 1e-07, 1e-06, 1e-05, 0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, 10000000.0, 100000000.0, 1000000000.0],
           class_weight=None, cv=5, dual=False, fit_intercept=True,
           intercept_scaling=1.0, max_iter=10000, multi_class='warn',
           n_jobs=None, penalty='l2', random_state=777, refit=True,
           scoring='roc_auc', solver='newton-cg', tol=10, verbose=0)

In [39]:
# look at important features.
print(pd.Series((np.std(X, 0)*clf.coef_)[0, :], index=selected_features[:21]))

funding_total_usd                 6.028292
status_feature                    0.069733
country_feature                   0.205482
age_feature                      -0.177656
days_since_first_funding         -0.122888
all_tweet_num                    79.271077
preA_tweet_num                    0.580028
postA_tweet_num                  71.683538
preA_tweet_freq                 -20.690736
postA_tweet_freq                -36.225650
preA_tweet_avglength             -0.194989
postA_tweet_avglength            -0.037065
preA_tweet_content_richness       0.092500
postA_tweet_content_richness      0.067240
preA_tweet_interactiveness       -0.239596
postA_tweet_interactiveness       0.093576
tweet_num_change                 66.255651
tweet_freq_change               -21.672747
tweet_avglength_change            0.114076
tweet_content_richness_change    -0.063398
tweet_interactiveness_change      0.667456
dtype: float64



In [45]:
# Grid search for logistic model.
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split, KFold, RandomizedSearchCV, GridSearchCV
from sklearn.linear_model import LogisticRegression

logistic = LogisticRegression()

penalty = ['l1', 'l2']
C = np.logspace(0, 4, 10)

hyperparameters = dict(C=C, penalty=penalty)
clf = GridSearchCV(logistic, hyperparameters, cv=5, verbose=0)
best_model = clf.fit(X, y)

print('Best Penalty: ', best_model.best_estimator_.get_params()['penalty'])
print('Best C: ', best_model.best_estimator_.get_params()['C'])

KeyboardInterrupt: 

In [56]:
# The above code finds the values for Best penalty as ‘xxx’ and best C is ‘xxx’.
# Now let’s use these values and calculate the accuracy.
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import SCORERS

# all scoring metrics
# print(sorted(SCORERS.keys()))

# cross-validation.
kfold = KFold(n_splits=5, random_state=7)
model = LogisticRegression(C=1, penalty='l2')
result = cross_val_score(model, X, y, cv=kfold, scoring='accuracy')
print("Accuracy: ", result.mean())

['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 'balanced_accuracy', 'brier_score_loss', 'completeness_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'mutual_info_score', 'neg_log_loss', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_median_absolute_error', 'normalized_mutual_info_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc', 'v_measure_score']
Accuracy:  0.7632101058889095


In [72]:
# Random forest model.
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split  

X_train, X_test, y_train, y_test = train_test_split(X[:, 1:], y, test_size=0.3, random_state=10)

# Create the model with 100 trees
clf = RandomForestClassifier(max_depth=5, n_estimators=20, random_state=7, oob_score=True)
clf.fit(X_train, y_train)

# Accuracy
print("Accuracy: ", clf.score(X_test, y_test))
print("OOB score: ", clf.oob_score_)

# feature importances.
print(pd.Series(clf.feature_importances_, index=selected_features[1:21]))

Accuracy:  0.8727272727272727
OOB score:  0.8306092124814265
status_feature                   0.011355
country_feature                  0.006849
age_feature                      0.029595
days_since_first_funding         0.096467
all_tweet_num                    0.138967
preA_tweet_num                   0.014351
postA_tweet_num                  0.146887
preA_tweet_freq                  0.014912
postA_tweet_freq                 0.061250
preA_tweet_avglength             0.017670
postA_tweet_avglength            0.008497
preA_tweet_content_richness      0.006988
postA_tweet_content_richness     0.032619
preA_tweet_interactiveness       0.005665
postA_tweet_interactiveness      0.062608
tweet_num_change                 0.145143
tweet_freq_change                0.065611
tweet_avglength_change           0.019511
tweet_content_richness_change    0.052510
tweet_interactiveness_change     0.062545
dtype: float64


In [78]:
# XGBoost model.
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
scaler = MinMaxScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

# split training feature and target sets into training and validation subsets
from sklearn.model_selection import train_test_split
X_train_sub, X_validation_sub, y_train_sub, y_validation_sub = train_test_split(X_train_scale, y_train, random_state=0)

# import machine learning algorithms
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc

# train with Gradient Boosting algorithm
# compute the accuracy scores on train and validation sets when training with different learning rates

learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1, 2, 5, 10]
for learning_rate in learning_rates:
    gb = GradientBoostingClassifier(n_estimators=20, learning_rate = learning_rate, max_features=2, max_depth = 2, random_state = 0)
    gb.fit(X_train_sub, y_train_sub)
    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(gb.score(X_train_sub, y_train_sub)))
    print("Accuracy score (validation): {0:.3f}".format(gb.score(X_validation_sub, y_validation_sub)))
    print()
    
# Output confusion matrix and classification report of Gradient Boosting algorithm on validation set
gb = GradientBoostingClassifier(n_estimators=20, learning_rate = 1.0, max_features=2, max_depth = 2, random_state = 0)
gb.fit(X_train_sub, y_train_sub)
predictions = gb.predict(X_validation_sub)
print("Confusion Matrix:")
print(confusion_matrix(y_validation_sub, predictions))
print()
print("Classification Report")
print(classification_report(y_validation_sub, predictions))

# ROC curve and Area-Under-Curve (AUC)
y_scores_gb = gb.decision_function(X_validation_sub)
fpr_gb, tpr_gb, _ = roc_curve(y_validation_sub, y_scores_gb)
roc_auc_gb = auc(fpr_gb, tpr_gb)

print("Area under ROC curve = {:0.2f}".format(roc_auc_gb))

# feature importances.
print(pd.Series(gb.feature_importances_, index=selected_features[1:21]))

Learning rate:  0.05
Accuracy score (training): 0.734
Accuracy score (validation): 0.710

Learning rate:  0.1
Accuracy score (training): 0.782
Accuracy score (validation): 0.744

Learning rate:  0.25
Accuracy score (training): 0.825
Accuracy score (validation): 0.771

Learning rate:  0.5
Accuracy score (training): 0.853
Accuracy score (validation): 0.805

Learning rate:  0.75
Accuracy score (training): 0.871
Accuracy score (validation): 0.816

Learning rate:  1
Accuracy score (training): 0.876
Accuracy score (validation): 0.817

Learning rate:  2
Accuracy score (training): 0.668
Accuracy score (validation): 0.654

Learning rate:  5
Accuracy score (training): 0.473
Accuracy score (validation): 0.425

Learning rate:  10
Accuracy score (training): 0.613
Accuracy score (validation): 0.618

Confusion Matrix:
[[207  58]
 [ 65 343]]

Classification Report
              precision    recall  f1-score   support

           0       0.76      0.78      0.77       265
           1       0.86      0

In [102]:
# Use Random forest and XG-Boost to predict time?
df_pos = df[df.WILL == 1.0].copy()
df_when = df_pos[selected_features[:-1]]
df_when['WHEN'] = pd.cut(x=df_pos.WHEN,\
                         bins = [-1, 360, 720, 1080, 10000], \
                         labels = [0, 1, 2, 3])
X = df_when.iloc[:, :-1].values
y = df_when.iloc[:, -1].tolist()
# print(df_when.head())
# print(X.shape, y.shape)

In [104]:
# Random forest model.
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split  

X_train, X_test, y_train, y_test = train_test_split(X[:, 1:], y, test_size=0.25, random_state=7, shuffle=False)

# Create the model with 100 trees
clf = RandomForestClassifier(max_depth=5, n_estimators=20, random_state=7, oob_score=True)
clf.fit(X_train, y_train)

# Accuracy
print("Accuracy: ", clf.score(X_test, y_test))
print("OOB score: ", clf.oob_score_)

# feature importances.
print(pd.Series(clf.feature_importances_, index=selected_features[1:21]))

Accuracy:  0.5591766723842195
OOB score:  0.5171821305841925
status_feature                   0.006232
country_feature                  0.005366
age_feature                      0.120379
days_since_first_funding         0.150055
all_tweet_num                    0.051040
preA_tweet_num                   0.047880
postA_tweet_num                  0.081488
preA_tweet_freq                  0.026158
postA_tweet_freq                 0.065012
preA_tweet_avglength             0.050172
postA_tweet_avglength            0.029792
preA_tweet_content_richness      0.020146
postA_tweet_content_richness     0.047105
preA_tweet_interactiveness       0.016717
postA_tweet_interactiveness      0.028049
tweet_num_change                 0.053408
tweet_freq_change                0.069568
tweet_avglength_change           0.042975
tweet_content_richness_change    0.065803
tweet_interactiveness_change     0.022653
dtype: float64


In [106]:
# XGBoost model.
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
scaler = MinMaxScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

# split training feature and target sets into training and validation subsets
from sklearn.model_selection import train_test_split
X_train_sub, X_validation_sub, y_train_sub, y_validation_sub = train_test_split(X_train_scale, y_train, random_state=0)

# import machine learning algorithms
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc

# train with Gradient Boosting algorithm
# compute the accuracy scores on train and validation sets when training with different learning rates

learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1, 2, 5, 10]
for learning_rate in learning_rates:
    gb = GradientBoostingClassifier(n_estimators=20, learning_rate = learning_rate, max_features=2, max_depth = 2, random_state = 0)
    gb.fit(X_train_sub, y_train_sub)
    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(gb.score(X_train_sub, y_train_sub)))
    print("Accuracy score (validation): {0:.3f}".format(gb.score(X_validation_sub, y_validation_sub)))
    print()
    
# Output confusion matrix and classification report of Gradient Boosting algorithm on validation set
gb = GradientBoostingClassifier(n_estimators=20, learning_rate = 1.0, max_features=2, max_depth = 2, random_state = 0)
gb.fit(X_train_sub, y_train_sub)
predictions = gb.predict(X_validation_sub)
print("Confusion Matrix:")
print(confusion_matrix(y_validation_sub, predictions))
print()
print("Classification Report")
print(classification_report(y_validation_sub, predictions))

# feature importances.
print(pd.Series(gb.feature_importances_, index=selected_features[1:21]))

Learning rate:  0.05
Accuracy score (training): 0.556
Accuracy score (validation): 0.501

Learning rate:  0.1
Accuracy score (training): 0.564
Accuracy score (validation): 0.499

Learning rate:  0.25
Accuracy score (training): 0.591
Accuracy score (validation): 0.487

Learning rate:  0.5
Accuracy score (training): 0.649
Accuracy score (validation): 0.510

Learning rate:  0.75
Accuracy score (training): 0.674
Accuracy score (validation): 0.501

Learning rate:  1
Accuracy score (training): 0.694
Accuracy score (validation): 0.481

Learning rate:  2
Accuracy score (training): 0.409
Accuracy score (validation): 0.391

Learning rate:  5
Accuracy score (training): 0.062
Accuracy score (validation): 0.062

Learning rate:  10
Accuracy score (training): 0.118
Accuracy score (validation): 0.140

Confusion Matrix:
[[102  63   4   2]
 [ 62 100   6  10]
 [ 17  33   5   6]
 [  3  17   4   3]]

Classification Report
              precision    recall  f1-score   support

           0       0.55      0